services:
  back-end:
    build: 
      context: ./Java-Backend
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - mysql-container
    environment:
      DB_URL: jdbc:mysql://mysql-container/users_db
      DB_USERNAME: example_user
      DB_PASSWORD: password123
  front-end:
    build: 
      context: ./React-Frontend
      dockerfile: Dockerfile
    ports:
      - 5173:5173
    depends_on:
      - back-end
  mysql-container:
    image: mysql:8.3.0-oracle
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      MYSQL_DATABASE: users_db
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_USER: example_user
      MYSQL_PASSWORD: password123

volumes:
  dbdata:

